//Next
import Head from 'next/head'

//Componets Principais
import Header from '../components/Header/Header'
import Menu from '../components/Menu/Menu'
import Footer from '../components/footer/Footer'
import Newsletter from '../components/Newsletter/Newsletter'

//Componets Page
import Crumbeads from '../components/BreadcrumbPath/BreadcrumbPath'
import TitleBox from '../components/titleBoxes/TitleBoxes'
import FAQ from '../components/Doubts/FAQ/FAQ'
import Carrousel from '../components/Carrousel/Carrousel'


let paths = [
  {href: "/",pageName: "sales.com.br"},
  {href: "#",pageName: "Dúvidas", currentPage: true}
]

export default function Home() {
  return (
    <div className="page-container">
      <Head>
        <title>Sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Menu/>
      <Crumbeads pathDataArray={paths} />
      <main className="main">
          <TitleBox types="h1" title="Perguntas Frequentes" align="start" />
          <FAQ />
          <TitleBox types="h2" title="Navegue por Categorias" align="center" />
          <Carrousel modules={"Navegation"} slideScreamCount="4" nextSlideScreamCount="4" loop={true} lazy={true} slides={["Boletos", "Trocas e Devoluções"]} />
          <Newsletter />
      </main>
      <Footer />
    </div>
  )
}
