import Head from 'next/head'
import Header from '../components/Header/Header'
import Menu from '../components/Menu/Menu'
import Footer from '../components/footer/Footer'
import Categories from '../components/HomeSections/Categories/Categories'
import FeaturedProducts from '../components/HomeSections/FeaturedProducts/FeaturedProducts'
import Suppliers from '../components/HomeSections/Suppliers/Suppliers'
import MainBanner from '../components/Banners/Home/MainBanner/MainBanner'
import SubBanner from '../components/Banners/Home/SubBanner/SubBanner'
import Newsletter from '../components/Newsletter/Newsletter'

import styles from '../styles/Home.module.css'

const featuredProductsData = ["Novo", "Produtos de Limpeza", "Papéis"];

export default function Home() {
  return (
    <div className="page-container">
      <Head>
        <title>Sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Menu/>
      <main className="main">
        <MainBanner />
        <span className={styles.navigateBy}>Navegue por</span>
        <Categories />
        {
          featuredProductsData.map((data, index) => {
            return <FeaturedProducts key={index} id={index} title={data} />
          })
        }
        <SubBanner />
        <Newsletter />
        <Suppliers />
      </main>
      <Footer />
    </div>
  )
}
