//Imports Next
import Head from 'next/head';
//Componentes
import Header from '../components/Header/Header'
import Menu from '../components/Menu/Menu'
import Policies from '../components/Policies/Policies'
import Crumbeads from '../components/BreadcrumbPath/BreadcrumbPath'
import Footer from '../components/footer/Footer'
import Newsletter from '../components/Newsletter/Newsletter'
import Duvidas from '../components/Duvidas/DuvidasFrequentes/Duvidas'

export default function Politicas() {

    const CrumB = [
      {href: "/",pageName: "sales.com.br"},
      {href: "#",pageName: "Políticas", currentPage: true}
    ];

    return (
        <div className="page-container">
      <Head>
        <title>Sales</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Menu/>
      <Crumbeads pathDataArray={CrumB} />
      <main className="main">
          <Policies />
          <Duvidas />
          <Newsletter />
      </main>
      <Footer />
    </div>
    )
}